### ISSUE TITLE
Plotting shapes

### ISSUE THREAD

**Issue by crooksey** [MatthewDaws/TileMapBase#1]
Hi Matthew,

This is a fantastic project, thanks so much for making it open source! I was using plain old matplotlib basemap for my plotting, but overlaying my maps with OSM tiles is a big improvement. One things which I cannot seem to do is plot shapes.

For example in matplotlib, I can do:

```
# bbox is my bounding box data
map = Basemap(
            llcrnrlon=bbox.minx,llcrnrlat=bbox.miny,
            urcrnrlon=bbox.maxx,urcrnrlat=bbox.maxy,
            resolution='i', projection='tmerc', 
            lat_0 = central_lat, lon_0 = central_lng)

map.drawmapboundary(fill_color='aqua')
map.fillcontinents(color='coral',lake_color='aqua')
map.drawcoastlines()
map.drawrivers(color='#0000ff')
x,y = map(lngs, lats) # build line data
map.plot(x, y, 'ro-') # plot lines
plt.show()
```

Which would generate:
![figure_1](https://user-images.githubusercontent.com/862603/33708107-6f51de92-db31-11e7-961c-80f13078ca72.png)

This plots each point and a line between them (a polyline). How would I plot points and lines in the same way on TileMapBase?

**Comment by MatthewDaws** [comment]
TileMapBase isn't a self-contained plotting environment; it just plots basemaps into a standard matplotlib axes object.  So, as long as you project to the correct coordinate system, you can use any of the usual matplotlib commands to add lines etc. etc.

I added an example here:
https://github.com/MatthewDaws/TileMapBase/blob/master/notebooks/Plotting%20over%20a%20basemap.ipynb
which does this.  Hope it helps.

**Comment by crooksey** [comment]
Hi Matthew,

Thanks for replying, that makes sense. Coming from matplotlib to this project there was another question I wanted to ask, how do you calculate the aspect for the basemap, to ensure the rendered map displays the co-ordinates supplied.

See example below of a basic matplotlib map:
```python
bbox.minx = -2.8197899
bbox.maxx = -0.691999
bbox.miny = 50.5380771
bbox.maxy = 50.8583224
central_lat = 50.73299110909091
central_lng = -2.038488663636364

# Matplotlib example
map = Basemap(
            llcrnrlon=bbox.minx,llcrnrlat=bbox.miny,
            urcrnrlon=bbox.maxx,urcrnrlat=bbox.maxy,
            resolution='h', projection='tmerc', 
            lat_0 = central_lat, lon_0 = central_lng
            )

map.drawmapboundary(fill_color='aqua')
map.fillcontinents(color='green',lake_color='aqua')
map.drawcoastlines()
map.drawrivers(color='#0000ff')
plt.savefig('example_matplotlib.png', bbox_inches='tight')
```
![test](https://user-images.githubusercontent.com/862603/33763405-4dd4892c-dc08-11e7-84fd-fa873bb187be.png)

Now if I try to render this same map using TileMapBase with the below code:
```python
t = tilemapbase.tiles.OSM
extent = tilemapbase.Extent.from_lonlat(
                longitude_min=bbox.minx, 
                longitude_max=bbox.maxx,
                latitude_min=bbox.miny, 
                latitude_max=bbox.maxy)
extent = extent.to_aspect(1)
fig, ax = plt.subplots(figsize=(8, 8), dpi=100)
ax.xaxis.set_visible(False)
ax.yaxis.set_visible(False)
plotter = tilemapbase.Plotter(extent, t, width=600)
plotter.plot(ax, t)
plotter.plotlq(ax, t)
fig.savefig("example_tilemap.png", dpi=200)
```
![67](https://user-images.githubusercontent.com/862603/33763436-71a18aa8-dc08-11e7-9ec0-bd7c83a8515b.png)

You can see that my maxX and maxY points do not even appear on this map, this is where they actually are: https://osmaps.ordnancesurvey.co.uk/50.85832,-0.69201,15/pin

Obviously in my code I can increase my aspect value so more of the map is shown, but when generating lots of maps dynamically, I need to be able to calculate this value so that all areas of the map are shown, how can I do this, or given my input data should I be generating the basemap a different way?

**Comment by MatthewDaws** [comment]
I opened a new issue for this 2nd question: https://github.com/MatthewDaws/TileMapBase/issues/2

**Comment by jeffcsauer** [comment]
Don't mean to necro this post, but what if we have many geopandas-style shapes that we would like to plot - do we have to use the `tilemapbase.project()` function? 

Was wondering if there was any way to go the other way - say I have my tilemapbase set up and everything is great, but I actually want to convert the tilemapbase to another projection. Thoughts?

**Comment by MatthewDaws** [comment]
I don't understand the 2nd question: tiles are raster images, so they come with a projection, and cannot be reprojected.  (Without image processing, which is far outside the scope of this project).

For the 1st question: tiles are projected in a standard "web mercator" projection, so you should just be able to project using whatever software package you like...

I designed `tilemapbase` as a very lightweight project, with one aim.  I don't intend to extend it.
