### ISSUE TITLE
Noisy pyproj error

### ISSUE THREAD

**Issue by jmcker** [MatthewDaws/TileMapBase#13]
Is there a reason you log the `Failed to load module 'pyproj'.` message using `logging.error`?

The error fires on import of `mapping.py` and/or `ordnancesurvey.py`. To the unobservant or novice user, it looks like a failure.

The comment on [line 582](https://github.com/MatthewDaws/TileMapBase/blob/171149738c4a890a583811978b121a186289e3ae/tilemapbase/mapping.py#L582) notes that `pyproj` is optional. Would it be appropriate to keep the message out of `stderr` for people opting not to use it, but still let it log somewhere (maybe `info` or `debug`) for those using `pyproj`?

**Comment by MatthewDaws** [comment]
Yes, I think I now agree, and I will remove these logs as I fix the `pyproj` issues.
