### ISSUE TITLE
Problem with Pyproj '2.6.1.post1'

### ISSUE THREAD

**Issue by campurol** [MatthewDaws/TileMapBase#19]
Pyproj changed the way it handles projections. Now, I get `TypeError: 'CRS' object is not subscriptable` when I try to generate an extent based on a frame that has their CRS set with the new pyproj. 

The difference is clear from reading the following geopandas docu
https://geopandas.org/projections.html
So now, the CRS object is not subscriptable as before and also it give you back a description of the projection which is different from older versions. 

I think the way to fix it should be relatively straighforward by updating some of the lines in the  `_parse_crs(crs)` function from `mapping.py` but I'm not sure because I haven't gone through the whole set of the code.

**Comment by ClaCodes** [comment]
Do to the changes in pyproj I get the following future warning.

Maybe they can be addressed aswell?

> /usr/local/lib/python3.8/dist-packages/pyproj/crs/crs.py:53: FutureWarning: '+init=<authority>:<code>' syntax is deprecated. '<authority>:<code>' is the preferred initialization method. When making the change, be mindful of axis order changes: https://pyproj4.github.io/pyproj/stable/gotchas.html#axis-order-changes-in-proj-6
>   return _prepare_from_string(" ".join(pjargs))

**Comment by MatthewDaws** [comment]
The future warning is being fixed as part of another issue.

I then need to look at **geoPanadas**.

**Comment by MatthewDaws** [comment]
Have now fixed the geoPandas parsing code, and written some tests around the code as well.  Both old a new geoPandas should be supported now.
