### ISSUE TITLE
Using outdated PIL library

### ISSUE THREAD

**Issue by james-willcox** [MatthewDaws/TileMapBase#21]
Having compatibility issue with the old PIL library, it needs to be the new Pillow library and then the imports PIL need to be changed to pil

**Comment by MatthewDaws** [comment]
Hi, I'm a bit confused by this.  I thought pillow was essentially completely standard now.  It _is_ what I am using, see the `requirements.txt` file.  But I thought you still imported it as `PIL`.  See the docs, for example:
https://pillow.readthedocs.io/en/stable/handbook/tutorial.html#using-the-image-class

Could you post some more information about your setup, and the exact error message (or problem) you're getting?

**Comment by james-willcox** [comment]
Nope sorry figured out what it was.  There is a pillow package and a Pillow package, I had both installed and pillow was being imported rather than Pillow.  Happy to close this

**Comment by james-willcox** [comment]
Also, love the package!  Thanks
