### ISSUE TITLE
Future warning: deprecated syntax

### ISSUE THREAD

**Issue by james-willcox** [MatthewDaws/TileMapBase#22]
FutureWarning: '+init=<authority>:<code>' syntax is deprecated. '<authority>:<code>' is the preferred initialization method. When making the change, be mindful of axis order changes: https://pyproj4.github.io/pyproj/stable/gotchas.html#axis-order-changes-in-proj-6
  return _prepare_from_string(" ".join(pjargs))

**Comment by MatthewDaws** [comment]
Duplicate of
https://github.com/MatthewDaws/TileMapBase/issues/17

Now fixed.

**Comment by james-willcox** [comment]
Thanks
