### ISSUE TITLE
Error handling function tilemapbase.Extent.from_lonlat

### ISSUE THREAD

**Issue by james-willcox** [MatthewDaws/TileMapBase#23]
There is no error handling if you get your latitude and longitude the wrong way around.  The only error you get is:

```
line 3326, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-1-d31946b083ef>", line 1, in <module>
    ytile = (1.0 - _math.log(_math.tan(lat_rad) + (1 / _math.cos(lat_rad))) / _math.pi) / 2.0
ValueError: math domain error```

**Comment by MatthewDaws** [comment]
In general, I don't like value checking (caller's responsibility and all that).  But I also endlessly get lon/lat swapped, and this is a nice idea.  Now implemented:

    tilemapbase.mapping.project(80,170)
    ....
    ValueError: Longitude/Latitude (80/170) is out of valid range [-180,180] / [-90,90].  Did you swap them around?
