### ISSUE TITLE
tilemapbase_cache.db does no exist and no request made to create

### ISSUE THREAD

**Issue by kanguuu10** [MatthewDaws/TileMapBase#29]
while using the library I get the following error
Exception: The database cache file C:\Users\user\tilemapbase_cache.db does no exist and no request made to create.
This could be caused by:
- Running the package for the first time.  To be paranoid, we do not automatically create a new cache.  Run `init(create=True)` to initise the cache.
- You have run the package before, but the cache has been lost. Check that the filename is correct.

the error message suggest running `init(create=True)`. Could you please tell how to do it? where should I type this 'init' thing?

**Comment by MatthewDaws** [comment]
Please see this minimal working example:
https://github.com/MatthewDaws/TileMapBase/blob/master/notebooks/Example.ipynb
The 3rd cell in the notebook shows how to create the cache.
