### ISSUE TITLE
Requested region does not display properly

### ISSUE THREAD

**Issue by shivariyer** [MatthewDaws/TileMapBase#7]
Hello,

I want to plot a bunch of locations (given as coordinates) on a map and found tilemapbase to be a good tool for the task. I modified the code from Example.ipynb for the task, by changing the coordinates of the center of the map to (18.932583, 72.831183) (a location in Mumbai in India). When I run the code, only a blank map appears.

I tried with New York City, and it's again blank. But it displays correctly for the default location in London hardcoded in Example.ipynb.

Why is this the case? Are the tiles not available for other locations? Or is it something else?

Follow up question: I downloaded my required area in mbtiles format from openmaptiles.com. Is it possible to use offline tiles in tilemapbase?

Thanks!
Shiva

```python
# Sample plotting of map in Mumbai area
import matplotlib.pyplot as plt
```

```python
import tilemapbase
tilemapbase.start_logging()
```

```python
# use openstreetmap (OSM)
t = tilemapbase.tiles.OSM
```

```python
coords = (18.932583, 72.831183)
# coords = (-1.554934, 53.804198)
# coords = (40.762548, -73.980240)
degree_range = 0.003
extent = tilemapbase.Extent.from_lonlat(coords[0] - degree_range, coords[0] + degree_range, coords[1] - degree_range, coords[1] + degree_range)
extent = extent.to_aspect(1.0)
extent
```

    Extent((0.552582175,0.1990682936246924)->(0.5525988416666667,0.19908496029135905) projected as normal)

```python
fig, ax = plt.subplots(figsize=(8,8), dpi=100)
ax.xaxis.set_visible(False)
ax.yaxis.set_visible(False)

plotter = tilemapbase.Plotter(extent, t, width=600)
plotter.plot(ax, t)
```

![output_4_0](https://user-images.githubusercontent.com/8555487/43778989-cedd7be8-9a74-11e8-8362-bb8085ea60c0.png)

**Comment by jbndlr** [comment]
Coordinates are to be provided in order (1) longitude, (2) latitude. If you copied them from Google Maps, they will be in lat/lon order and you have to flip them. So your map image is not empty, it's just a location in the ocean north of Norway.

**Comment by MatthewDaws** [comment]
Yes, when I wrote the code, it seemed that there wasn't a universal standard for ordering.  So I chose the one which is different to Google Maps.  The method name `from_lonlat` should give a hint as to the correct ordering...

**Comment by shivariyer** [comment]
Thank you @jbndlr and @MatthewDaws! It works now after flipping lat and lon. Can't believe I failed to notice that...
