### ISSUE TITLE
Failed install: egg_info failed 

### ISSUE THREAD

**Issue by profitis** [MatthewDaws/TileMapBase#8]
Hello all,

I tried to install TileMapBase to my machine (both via pip and directly via GitHub), but I got these messages:

> manos@xxx:~$ pip install tilemapbase
Collecting tilemapbase
  Could not find a version that satisfies the requirement tilemapbase (from versions: )
No matching distribution found for tilemapbase
You are using pip version 10.0.1, however version 18.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
manos@xxx:~$ 
manos@xxx:~$ 
manos@xxx:~$ 
manos@xxx:~$ pip install https://github.com/MatthewDaws/TileMapBase/zipball/master
Collecting https://github.com/MatthewDaws/TileMapBase/zipball/master
  Downloading https://github.com/MatthewDaws/TileMapBase/zipball/master
     - 13.1MB 56.1MB/s
    Complete output from command python setup.py egg_info:
    NOT REFRESHING README.rst
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-req-build-AgObC0/setup.py", line 22, in <module>
        with open('README.rst', encoding='utf-8') as f:
    TypeError: 'encoding' is an invalid keyword argument for this function
    
    ----------------------------------------
>Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-req-build-AgObC0/
You are using pip version 10.0.1, however version 18.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.

**Comment by MatthewDaws** [comment]
What version of Python are you on?  The exception is being thrown from this line of `setup.py`:

> with open('README.rst', encoding='utf-8') as f:

with a complaint that the interpreter doesn't understand the keyword `encoding`.  It definitely _is_ a keyword in version 3.5 onwards!

What does the following give you:

> python
> import sys
> sys.version

I see `3.6.5 |Anaconda, Inc.| (default, Mar 29 2018, 13:32:41) [MSC v.1900 64 bit (AMD64)]`

**Comment by profitis** [comment]
> What version of Python are you on? The exception is being thrown from this line of `setup.py`:

I use Python 2.7.15 Anaconda Custom

Many thanks for the instant reply!

**Comment by MatthewDaws** [comment]
Yes, Python 3 only, I'm afraid.
